# Deliberately NO include guard: CANN 8.5 creates this target on each include.
if(NOT PREFILL_ENUMERATE_ONLY)
  add_library(host_intf_pub INTERFACE)
  set(PREFILL_FAKE_CANN_READY TRUE)
endif()

function(ascendc_library_with_def target kind)
  if(PREFILL_ENUMERATE_ONLY)
    set_property(GLOBAL PROPERTY PREFILL_VENDOR_SOURCES ${ARGN})
    return()
  endif()
  if(NOT PREFILL_FAKE_CANN_READY)
    message(FATAL_ERROR "AscendC configuration lost across directory scopes")
  endif()
  add_library(${target} INTERFACE)
  set_target_properties(${target} PROPERTIES
    PREFILL_SOURCES "${ARGN}" PREFILL_TYPE "${kind}")
  if(CMAKE_CURRENT_SOURCE_DIR MATCHES "/third_party/kvcache-ops$")
    set_property(GLOBAL PROPERTY PREFILL_VENDOR_SOURCES ${ARGN})
  endif()
endfunction()
function(ascendc_library)
  ascendc_library_with_def(${ARGV})
endfunction()
function(ascendc_compile_definitions target visibility)
  if(NOT PREFILL_ENUMERATE_ONLY)
    set_property(TARGET ${target} APPEND PROPERTY PREFILL_DEFINITIONS ${ARGN})
  endif()
endfunction()
function(ascendc_include_directories target visibility)
  set_property(TARGET ${target} APPEND PROPERTY PREFILL_DEVICE_INCLUDES ${ARGN})
endfunction()
